// GENERATED by tools/build-extensions.mjs - do not edit.
// Service-worker half of the GM_xmlhttpRequest shim in slack-ai-translate.js.
chrome.runtime.onMessage.addListener((msg, sender, sendResponse) => {
    if (msg?.__gm !== 'xhr') return;
    const ctl = new AbortController();
    const timer = msg.timeout ? setTimeout(() => ctl.abort(), msg.timeout) : null;
    fetch(msg.url, { method: msg.method, headers: msg.headers, body: msg.data, signal: ctl.signal })
        .then(async (r) => sendResponse({ status: r.status, responseText: await r.text() }))
        .catch(() => sendResponse(ctl.signal.aborted ? { timeout: true } : { error: 'network' }))
        .finally(() => timer && clearTimeout(timer));
    return true;
});
