// GENERATED by tools/build-extensions.mjs - do not edit.
// Service-worker half of the GM_xmlhttpRequest shim in slack-ai-translate.js.
// Tampermonkey's GM_xmlhttpRequest sends no Origin header, and servers that check it
// reject browser origins outright (Ollama answers 403 to any Origin, including a
// chrome-extension:// one). fetch() cannot drop Origin, so a session rule strips it from
// this worker's own requests - tabId -1 - leaving page-initiated requests alone.
const originStripHosts = (chrome.runtime.getManifest().host_permissions || [])
    .map((pattern) => pattern.match(/^[a-z*]+:\/\/([^/*]+)/)?.[1])
    .filter(Boolean);
if (originStripHosts.length) {
    chrome.declarativeNetRequest.updateSessionRules({
        removeRuleIds: [1],
        addRules: [{
            id: 1,
            priority: 1,
            action: { type: 'modifyHeaders', requestHeaders: [{ header: 'origin', operation: 'remove' }] },
            condition: { requestDomains: originStripHosts, tabIds: [-1], resourceTypes: ['xmlhttprequest'] }
        }]
    });
}

chrome.runtime.onMessage.addListener((msg, sender, sendResponse) => {
    if (msg?.__gm !== 'xhr') return;
    const ctl = new AbortController();
    const timer = msg.timeout ? setTimeout(() => ctl.abort(), msg.timeout) : null;
    fetch(msg.url, { method: msg.method, headers: msg.headers, body: msg.data, signal: ctl.signal })
        .then(async (r) => sendResponse({ status: r.status, responseText: await r.text() }))
        .catch(() => sendResponse(ctl.signal.aborted ? { timeout: true } : { error: 'network' }))
        .finally(() => timer && clearTimeout(timer));
    return true;
});
